highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Twin Karmakharm's Resume
name: Twin Karmakharm
jobtitle: Research Software Engineer
email: t.karmakharm@sheffield.ac.uk
email_full: mailto:t.karmakharm@sheffield.ac.uk
website: twin.uk.com
website_full: https://twin.uk.com
github: twinkarma
twitter: twin_karma
#tel: +44 0000 000000
#tel_full: tel:+440000000000
google_maps: 'https://goo.gl/maps/p7FD9DPHKCD2'
address: Computer Science Department<br/> University of Sheffield<br/> 211 Portobello
postcode: S1 4DP
city: Sheffield
country: United Kingdom
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
